### ISSUE TITLE
CDN issues - map not loading

### ISSUE THREAD

**Issue by mariogiampieri** [596acres/urbanreviewer#16]
Thanks for all of your work on this over the years! I was reminded of this project and was hoping to use it as a reference.

Hi, I see that the leaflet js and css files are not being properly loaded via CDN:
<img width="822" alt="image" src="https://github.com/user-attachments/assets/49ec0d0f-664c-4294-b413-803b688c1f8d">

When I follow the js CDN link, I see an expired certificate on https://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css. It appears that this is causing a set of downstream errors where `L` is not defined. I imagine that changing the CDN provider to something like https://cdnjs.com/libraries/leaflet/0.7.3 would solve this issue. I would be happy to open a PR if that's helpful. I see that the github pages version of the site does load correctly.

**Comment by ebrelsford** [comment]
Please use the version deployed at https://596acres.github.io/urbanreviewer/ as we no longer have access to the other domain.

**Comment by mariogiampieri** [comment]
Great, thanks for clarifying!
